version: '3.8'

services:
  database:
    image: postgres:16.2-alpine
    container_name: database
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - 5432:5432
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - database
